### ISSUE TITLE
Count method not working anymore on query builder

### ISSUE THREAD

**Issue by flexid** [visoft/ruby_odata#63]
Since the 2.x version the interfacing crashes on the count method.

```
NoMethodError: undefined method `count' for #<OData::QueryBuilder:0x0000020876e760>
```

This always worked:

`service.radiator_variants.filter("changed_on ge DATETIME'#{start_date}'").count`

Anyone else having this problem? Thanks

**Comment by visoft** [comment]
Hi @flexid, what ended up being the problem?
