### ISSUE TITLE
URI::InvalidURIError: bad URI(is not URI?)

### ISSUE THREAD

**Issue by nvchernov** [visoft/ruby_odata#69]
Hi! I have a problem while using ruby_odata, here my code

    @svc.AddToCatalog_Организации(
        {
            ФамилияИП: 'test_second_name',
            ИмяИП: 'test_third_name',
            ИНН: '344100591639'
        })
    category = @svc.save_changes

As you can see, it contains russian characters. ruby_odata works good with reading data, but if I trying to add data I getting this error:
URI::InvalidURIError: bad URI(is not URI?): http://my_ip/BP/odata/standard.odata/Catalog_Организации

I solve it by using this [commit](https://github.com/nvchernov/ruby_odata/commit/6626aac461d300595828b10132677effa3d89e51)

but I get another problem 
OData::ServiceError: XML parsing error:  - [1,1]
Fatal error: 
Document is empty

I know that problem appeared because server respond xml not json

any ides?

**Comment by visoft** [comment]
Is your service returning JSON or XML? Currently ruby_odata only supports XML.
